import React from 'react'
import refVar from "../mystyle.module.css";
const Mypara = () => {
    return (
        <div className={refVar.Para}>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Ea, soluta. Doloribus illo, at vero ex delectus odio architecto fuga! Atque neque voluptatibus natus. Atque saepe facere iste cupiditate corporis voluptate eveniet ullam quia ab expedita. Dolores, quis tempore delectus dicta quam consequatur beatae ab voluptates accusamus nemo asperiores sunt sequi architecto ipsam repudiandae aliquam laboriosam placeat quod nisi officiis voluptatum nihil reprehenderit expedita! Explicabo, illum neque soluta hic cupiditate quod libero eligendi facere reiciendis quisquam quasi amet iste harum accusantium recusandae debitis doloremque qui pariatur sit, modi blanditiis enim officiis quaerat delectus. Modi, perferendis facere. Nesciunt sequi quas nam saepe. Lorem ipsum dolor sit amet consectetur adipisicing elit. Illo fugiat et praesentium iure natus obcaecati, dicta quis? A, consectetur libero et possimus obcaecati laudantium dolorem. Dicta, ipsam ea. Minima commodi odit necessitatibus nostrum, deleniti veritatis. Quos adipisci quia est suscipit incidunt, possimus alias reprehenderit quae voluptatem vero architecto sapiente saepe asperiores deserunt nemo praesentium expedita aut ex odio debitis laboriosam fugiat pariatur dicta? Ipsam omnis odio explicabo deleniti quod earum magnam dolore eligendi nisi dicta, quae, quidem nulla itaque iste suscipit eaque ut aut architecto cupiditate facere fuga illum alias! Maiores ratione et vero eum magni distinctio expedita repudiandae similique ipsa pariatur. Minima praesentium pariatur libero accusantium, velit asperiores itaque iste beatae numquam aut porro id dignissimos? Eos voluptas quia placeat numquam repellendus id voluptates molestias ipsam eveniet! Ut culpa saepe minima explicabo vero unde exercitationem. Voluptatem ducimus ab impedit voluptates molestiae suscipit, nostrum vitae aspernatur soluta consequuntur perferendis eius. Eveniet, laboriosam facere. Eaque vel autem sapiente iure ipsum quisquam voluptatibus in corrupti, amet soluta, ipsam expedita, nostrum itaque accusamus sunt dolorum doloremque? Fugiat, labore eos at cumque quis voluptatem quibusdam doloribus! Delectus, voluptatibus quasi, sit aliquid hic ipsam amet eaque numquam illum, fugit omnis quia excepturi cumque eius nulla?
        </div>
    )
}

export default Mypara
